export const UI_STRINGS = {
  Search: "Search",
  WhereFrom: "Where from?",
  WhereTo: "Where to?",
  From: "From",
  To: "To",
  Flights: "Flights",
  RoundTrip: "Round trip",
  OneWay: "One-way",
  Adults: "Adults",
  Children: "Children",
  Aged: "Aged",
  Infants: "Infants",
  InSeat: "In seat",
  OnLap: "On lap",
  Economy: "Economy",
  PremiumEconomy: "Premium economy",
  Business: "Business",
  First: "First",
};
